// Copyright © SixtyFPS GmbH <info@slint-ui.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-commercial

import { ScrollView, Button, CheckBox, SpinBox, Slider, GroupBox, LineEdit, StandardListView,
    ComboBox, HorizontalBox, VerticalBox, GridBox, TabWidget, TextEdit, AboutSixtyFPS } from "std-widgets.slint";

App := Window {
    preferred-width: 1000px;
    preferred-height: 1000px;
    title: "Slint MPV";
    icon: @image-url("../../logo/slint-logo-small-light-128x128.png");

    property window_width <=> width;
    property window_height <=> height;
    property<bool> is_paused;

    VerticalBox {
        Rectangle {
            background: #ffffff00;
        }
        Rectangle {
            background: #ffffffaa;
            HorizontalBox {
                HorizontalLayout {
                    alignment: center;
                    Button {
                        width: 100px;
                        text: !is_paused ? "pause" : "play";
                        clicked => {
                            is_paused = !is_paused;
                        }
                    }
                }
            }
        }
    }
}
